/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.MantenimientoForms;

import Logger.EmpleadoLog;
import Model.Contrato;
import Model.Empleado;
import Model.Usuario;
import dao.Conexion;
import dao.ContratoDao;
import dao.UsuarioDao;
import dao.Utilitarios;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author clide
 */
public class Contratos extends javax.swing.JPanel {

    Conexion cnx = new Conexion();
    Connection cn = cnx.getCn();
    /**
     * Creates new form Empleados
     */
    Boolean editMode = false;
    ContratoDao contratoDao = new ContratoDao();
    EmpleadoLog empLog = new EmpleadoLog();
    Utilitarios utilitarios = new Utilitarios();
    public Contratos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Container = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtCodEmp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dcFecInicioContrato = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        cboArea = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        cboEstadoContrato = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtNumContrato = new javax.swing.JTextField();
        dcFecFinContrato = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        cboCargo = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSueldo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtareaObservaciones = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        cboSucursal = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JToggleButton();
        btnAgregarUsuario = new javax.swing.JToggleButton();
        btnEliminar = new javax.swing.JToggleButton();
        btnCancelar = new javax.swing.JToggleButton();
        Foto_Container = new javax.swing.JPanel();
        lblFotoUsr = new javax.swing.JLabel();
        lblRuta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContratos = new javax.swing.JTable();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos De Contratación\n"));

        txtCodEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodEmpActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo de Empleado :");

        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombresKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });

        jLabel2.setText("Nombres:");

        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosKeyTyped(evt);
            }
        });

        jLabel3.setText("Apellidos:");

        jLabel6.setText("Fecha de Inicio Contrato:");

        dcFecInicioContrato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dcFecInicioContratoKeyPressed(evt);
            }
        });

        jLabel18.setText("Estado de Contrato");

        cboArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel20.setText("Area:");

        cboEstadoContrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboEstadoContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEstadoContratoActionPerformed(evt);
            }
        });

        jLabel4.setText("Numero de Contrato:");

        txtNumContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumContratoActionPerformed(evt);
            }
        });
        txtNumContrato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumContratoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumContratoKeyTyped(evt);
            }
        });

        dcFecFinContrato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dcFecFinContratoKeyPressed(evt);
            }
        });

        jLabel7.setText("Fecha de Termino Contrato:");

        cboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel21.setText("Cargo:");

        jLabel5.setText("Sueldo:");

        txtSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSueldoActionPerformed(evt);
            }
        });
        txtSueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSueldoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSueldoKeyTyped(evt);
            }
        });

        jLabel8.setText("Observaciones:");

        txtareaObservaciones.setColumns(20);
        txtareaObservaciones.setRows(5);
        jScrollPane2.setViewportView(txtareaObservaciones);

        jLabel22.setText("Sucursal:");

        cboSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombres)
                            .addComponent(txtApellidos)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21)
                                .addComponent(jLabel20))
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboSucursal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dcFecFinContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSueldo)
                            .addComponent(cboCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNumContrato)
                            .addComponent(cboArea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dcFecInicioContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboEstadoContrato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                            .addComponent(txtCodEmp))))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dcFecInicioContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dcFecFinContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cboArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cboSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cboEstadoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(41, 41, 41))))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnAgregarUsuario.setText("Agregar Contrato");
        btnAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuarioActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar Registro");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        Foto_Container.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Foto de Empleado"));

        lblRuta.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        lblRuta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRuta.setText("jLabel19");

        javax.swing.GroupLayout Foto_ContainerLayout = new javax.swing.GroupLayout(Foto_Container);
        Foto_Container.setLayout(Foto_ContainerLayout);
        Foto_ContainerLayout.setHorizontalGroup(
            Foto_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFotoUsr, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
            .addComponent(lblRuta)
        );
        Foto_ContainerLayout.setVerticalGroup(
            Foto_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Foto_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFotoUsr, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRuta))
        );

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tblContratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblContratos.setAutoResizeMode(0);
        tblContratos.setAutoscrolls(false);
        tblContratos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblContratosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblContratos);

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContainerLayout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ContainerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ContainerLayout.createSequentialGroup()
                                .addComponent(Foto_Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(431, 431, 431)
                                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAgregarUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addGap(578, 578, 578)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Foto_Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ContainerLayout.createSequentialGroup()
                                .addComponent(btnAgregarUsuario)
                                .addGap(55, 55, 55)
                                .addComponent(btnCancelar)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addGap(168, 168, 168)))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtNombresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyPressed
        // TODO add your handling code here:
        utilitarios.Cambiar_Cursor(evt, txtApellidos);

    }//GEN-LAST:event_txtNombresKeyPressed

    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped

    }//GEN-LAST:event_txtNombresKeyTyped

    private void txtApellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyPressed

    }//GEN-LAST:event_txtApellidosKeyPressed

    private void txtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosKeyTyped

    private void dcFecInicioContratoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcFecInicioContratoKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_dcFecInicioContratoKeyPressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        Boolean agregarRegistro = contratoDao.agregarContrato(txtNumContrato.getText(), txtCodEmp.getText(), dcFecInicioContrato.getDate(), 
                dcFecFinContrato.getDate(),cboSucursal.getSelectedItem().toString(), cboArea.getSelectedItem().toString(), cboCargo.getSelectedItem().toString(), 
                Integer.parseInt( txtSueldo.getText()), this.cboEstadoContrato.getSelectedItem().toString(),txtareaObservaciones.getText() );
        if( agregarRegistro){
            JOptionPane.showMessageDialog(null,"Usuario  Agregado con exito");
            campos(false);
            botones(true);
            limpiarCampos();
            tblContratos.setModel(contratoDao.crearMdlContrato());
            editMode = false;
        }else{
            JOptionPane.showMessageDialog(null, "Registro No agregado","",0);
            campos(false);
            botones(true);
            limpiarCampos();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuarioActionPerformed
        // TODO add your handling code here:
        editMode = true;
        String codigo = JOptionPane.showInputDialog(null,"Ingrese Codigo del Empleado");
        Empleado emp = empLog.buscarEmp(codigo);
        if(emp != null){
            if(!empLog.contratoVigenteEmp(codigo)){
                JOptionPane.showMessageDialog(  null , "Registro Encontrado", "Proyecto", 3);
                limpiarCampos();
                cargarVistaNuevoContrato(emp);
                txtNumContrato.setText(contratoDao.generarNumContrato());
                botones(false);
                campos(true);
            }else{
                JOptionPane.showMessageDialog(  null ,"El empleado: " + codigo + "No se puede crear un nuevo contrato  \n El empleado ya tiene un Contrato Vigente", "Proyecto", 0);
            }

        }else{
            JOptionPane.showMessageDialog(  null , "No se ha encontrado en el registro, \n Para registrar un nuevo empleado vaye a Mantenimiento > Empleados", "Proyecto", 0);
        }

    }//GEN-LAST:event_btnAgregarUsuarioActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        /*int selected = tblContratos.getSelectedRow();
        if(selected != -1){
            String codEmp = tblContratos.getValueAt(selected,0).toString();
            if(usuDao.eliminarUsuario(codEmp)){
                JOptionPane.showMessageDialog(null,"Se ha eliminado la cuenta de usuario");
                tblContratos.setModel(usuDao.crearMdlUsuario());
                limpiarCampos();
            }else{
                JOptionPane.showMessageDialog(null, "Registro de empleado no encontrado");
            }
        }else{

        }*/

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        if(!editMode){
            limpiarCampos();
            botones(true);
            campos(false);
        }else{
            int Rpta = 0;
            Rpta = JOptionPane.showConfirmDialog(null,"SEGURO QUE DESEA SALIR?, LA CREACION DE USUARIO NO SE HA COMPLETADO","Mensaje al usuario",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(Rpta==0){
                limpiarCampos();
                botones(true);
                campos(false);
                editMode = false;
            }
        }

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tblContratosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContratosMouseClicked
        // TODO add your handling code here:
        if(!editMode){
            limpiarCampos();
            int selected = tblContratos.getSelectedRow();
            String codEmp = tblContratos.getValueAt(selected, 0).toString();
            
            Contrato contrato = contratoDao.crearContrato(codEmp);
            System.out.println(contrato.getCodEmp());
            cargarVista(contrato);
        }else{
            JOptionPane.showMessageDialog(null,"Tiene Datos que aun no ha guardado");
        }
    }//GEN-LAST:event_tblContratosMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
         tblContratos.setModel(contratoDao.crearMdlContrato());
        
        this.limpiarCampos();
        botones(true);
        campos(false);
    }//GEN-LAST:event_formAncestorAdded

    private void txtNumContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumContratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumContratoActionPerformed

    private void txtNumContratoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumContratoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumContratoKeyPressed

    private void txtNumContratoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumContratoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumContratoKeyTyped

    private void dcFecFinContratoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcFecFinContratoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dcFecFinContratoKeyPressed

    private void txtSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSueldoActionPerformed

    private void txtSueldoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSueldoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSueldoKeyPressed

    private void txtSueldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSueldoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSueldoKeyTyped

    private void txtCodEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodEmpActionPerformed

    private void cboEstadoContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEstadoContratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEstadoContratoActionPerformed

    void cargarVista(Contrato contrat){
       txtCodEmp.setText(contrat.getCodEmp());
       txtNumContrato.setText(contrat.getNumContrato());
       txtNombres.setText(contrat.getNombres());
       txtApellidos.setText(contrat.getApellidos());
       dcFecInicioContrato.setDate(contrat.getFecInicio());
       dcFecFinContrato.setDate(contrat.getFecFin());
       cboArea.setSelectedItem(contrat.getArea());
       cboCargo.setSelectedItem(contrat.getCargo());
       cboSucursal.setSelectedItem(contrat.getSucursal());
       cboEstadoContrato.setSelectedItem(contrat.getEstadoContrato());
       txtSueldo.setText(String.valueOf( contrat.getSueldo()));
       txtareaObservaciones.setText(contrat.getObs());
        cargarFoto(contrat.getFoto());
       
    }
    
    public void limpiarCampos(){
       txtCodEmp.setText("");
       txtNumContrato.setText("");
       txtNombres.setText("");
       txtApellidos.setText("");
       dcFecFinContrato.setDate(null);
       dcFecInicioContrato.setDate(null);
       cboArea.removeAllItems();
       cboArea.addItem("<SELECCIONE>");
       cboArea.addItem("Gerencia General");
       cboArea.addItem("Área de Finanzas y Administracion");
       cboArea.addItem("Área de Recursos Humanos");
       cboArea.addItem("Área de Logística");
       cboArea.addItem("Área de Almacén");
       cboArea.addItem("Área de Ventas");
       cboCargo.removeAllItems();
       cboCargo.addItem("<SELECCIONE>");
       cboCargo.addItem("Gerente General");
       cboCargo.addItem("Administrador de Sucursal");
       cboCargo.addItem("Administrador de Recursos Humanos");
       cboCargo.addItem("Jefe de Logística");
       cboCargo.addItem("Jefe de Almacén");
       cboCargo.addItem("Asistente de Almacén");
       cboCargo.addItem("Supervisor  de Almacén");
       cboCargo.addItem("Jefe de Ventas");
       cboCargo.addItem("Asistente de Ventas");
       cboSucursal.removeAllItems();
       cboSucursal.addItem("<SELECCIONE>");
       cboSucursal.addItem("Sucursal 01 - San Juan de Lurigancho");
       cboSucursal.addItem("Sucursal 02 - Puente Piedra");
       cboSucursal.addItem("Sucursal 03 - Villa El Salvador");
       cboEstadoContrato.removeAllItems();
       cboEstadoContrato.addItem("<SELECCIONE>");
       cboEstadoContrato.addItem("Vigente");
       cboEstadoContrato.addItem("Finalizado");
       txtSueldo.setText("");
       txtareaObservaciones.setText("");
       this.lblFotoUsr.setIcon(null);
    }
    void cargarVistaNuevoContrato(Empleado emp){
       txtCodEmp.setText(emp.getCod());
       
       txtNombres.setText(emp.getNombre());
       txtApellidos.setText(emp.getApellidos());
       Date now = new Date();
       // para formatear fecha: SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
       dcFecInicioContrato.setDate(now);
        
    }
    public void botones(boolean b){
        btnAgregarUsuario.setEnabled(b);
        btnGuardar.setEnabled(!b);
        btnCancelar.setEnabled(!b);
        btnEliminar.setEnabled(b);
    }
    
    public void campos(boolean b){
       txtCodEmp.setEnabled(false);
       txtNumContrato.setEnabled(false);
       txtNombres.setEnabled(false);
       txtApellidos.setEnabled(false);
       dcFecInicioContrato.setEnabled(false);
       cboArea.setEnabled(b);
       cboSucursal.setEnabled(b);
       cboEstadoContrato.setEnabled(b);
    }

    public void cargarCombo( JComboBox combo , String tbl, String dboCol) {
        combo.removeAllItems();
        combo.addItem("<SELECCIONE>");
        
        try{
           String sql = "select " + dboCol +  " from " + tbl;
           Statement st = cn.createStatement();
           ResultSet rs = st.executeQuery(sql);
           while(rs.next()){
               combo.addItem(rs.getString(1));
           }
        }catch(SQLException Error ){
             JOptionPane.showMessageDialog(null, "Error en Cargar Combo"+Error.getMessage(),null,
                                            JOptionPane.ERROR_MESSAGE);
        }

    }
    

    void cargarFoto(byte[] bytesArr){
        try {
            
            if(bytesArr != null){

                InputStream is = new ByteArrayInputStream(bytesArr);
                BufferedImage img = ImageIO.read(is);
                File archivo = new File("img.jpg");

                ImageIO.write(img, "jpg",archivo);

                ImageIcon imagen = new ImageIcon(archivo.getAbsolutePath());
                Icon icoImg = new ImageIcon(imagen.getImage().getScaledInstance(lblFotoUsr.getWidth(),lblFotoUsr.getHeight(), Image.SCALE_SMOOTH));
                lblFotoUsr.setIcon(icoImg);
            }else{
                JOptionPane.showMessageDialog(null, "No se ha encontrado una imagen en la base de datos del usuario");
            }
            
        } catch (IOException e) {
            System.out.println("Ha ocurrido un error garrafal " + e.getMessage()+  e.getStackTrace());
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JPanel Foto_Container;
    private javax.swing.JToggleButton btnAgregarUsuario;
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JToggleButton btnEliminar;
    private javax.swing.JToggleButton btnGuardar;
    private javax.swing.JComboBox<String> cboArea;
    private javax.swing.JComboBox<String> cboCargo;
    private javax.swing.JComboBox<String> cboEstadoContrato;
    private javax.swing.JComboBox<String> cboSucursal;
    private com.toedter.calendar.JDateChooser dcFecFinContrato;
    private com.toedter.calendar.JDateChooser dcFecInicioContrato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFotoUsr;
    private javax.swing.JLabel lblRuta;
    private javax.swing.JTable tblContratos;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCodEmp;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNumContrato;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JTextArea txtareaObservaciones;
    // End of variables declaration//GEN-END:variables
}
