/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.MantenimientoForms;

import Logger.EmpleadoLog;
import Model.Empleado;
import Model.Producto;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.common.BitMatrix;
import com.sun.imageio.plugins.png.RowFilter;
import dao.Conexion;
import dao.ProductosDao;
import dao.Utilitarios;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author clide
 */
public class MntProductos extends javax.swing.JPanel {

    
    Conexion cnx = new Conexion();
    Connection cn = cnx.getCn();
    /**
     * Creates new form Empleados
     */
    Boolean editMode = false;
    Utilitarios utilitarios = new Utilitarios();
    ProductosDao prodDao = new ProductosDao();
    
    TableRowSorter<DefaultTableModel> filtro; 
    //Datos del codigo de barra de producto generado
    String barcodeData;
    public MntProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedMntProd = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        FormRegEmp = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtCodReg = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPresentacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cboCategoria = new javax.swing.JComboBox<>();
        cboProducto = new javax.swing.JComboBox<>();
        cboMarca = new javax.swing.JComboBox<>();
        cboEstadoProd = new javax.swing.JComboBox<>();
        txtUniMed = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtPrecioUnit = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtPrecCaja = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtPrecVentaUnit = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtPrecVentaCaja = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtStockCajas = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtStockUnits = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JToggleButton();
        btnEditar = new javax.swing.JToggleButton();
        btnGuardar = new javax.swing.JToggleButton();
        btnNuevo = new javax.swing.JToggleButton();
        btnEliminar = new javax.swing.JToggleButton();
        btnCancelar = new javax.swing.JToggleButton();
        Foto_Container = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        lblRuta = new javax.swing.JLabel();
        btnExaminar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        txtBusqueda = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btnVerEnConsultas = new javax.swing.JButton();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos del Producto"));

        jLabel1.setText("Codigo de registro:");

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyTyped(evt);
            }
        });

        jLabel2.setText("Descripción del producto:");

        txtPresentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPresentacionActionPerformed(evt);
            }
        });
        txtPresentacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPresentacionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPresentacionKeyTyped(evt);
            }
        });

        jLabel3.setText("Presentación:");

        jLabel7.setText("Estado de Producto:");

        jLabel11.setText("Marca:");

        jLabel12.setText("Producto:");

        jLabel13.setText("Categoria:");

        cboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboCategoriaItemStateChanged(evt);
            }
        });

        cboProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboProducto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboProductoItemStateChanged(evt);
            }
        });

        cboMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboEstadoProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtUniMed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUniMedKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUniMedKeyTyped(evt);
            }
        });

        jLabel19.setText("Unidad de Medida:");

        txtPrecioUnit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecioUnitKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioUnitKeyTyped(evt);
            }
        });

        jLabel21.setText("Precio Unitario:");

        txtPrecCaja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecCajaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecCajaKeyTyped(evt);
            }
        });

        jLabel22.setText("Precio por Caja:");

        txtPrecVentaUnit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecVentaUnitKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecVentaUnitKeyTyped(evt);
            }
        });

        jLabel23.setText("Precio Unitario de Venta");

        txtPrecVentaCaja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecVentaCajaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecVentaCajaKeyTyped(evt);
            }
        });

        jLabel24.setText("Precio de Venta por Caja:");

        txtStockCajas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStockCajasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockCajasKeyTyped(evt);
            }
        });

        jLabel25.setText("Stock de Cajas:");

        txtStockUnits.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStockUnitsKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockUnitsKeyTyped(evt);
            }
        });

        jLabel26.setText("Stock de Unidades:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)))
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboEstadoProd, 0, 360, Short.MAX_VALUE)
                    .addComponent(txtStockUnits)
                    .addComponent(txtStockCajas)
                    .addComponent(txtPrecVentaCaja)
                    .addComponent(txtPrecCaja)
                    .addComponent(txtPrecioUnit)
                    .addComponent(txtUniMed)
                    .addComponent(txtCodReg)
                    .addComponent(txtPresentacion)
                    .addComponent(cboProducto, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDescripcion)
                    .addComponent(txtPrecVentaUnit))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUniMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecVentaUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecVentaCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStockCajas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStockUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboEstadoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        Foto_Container.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Foto del Producto"));

        lblRuta.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        lblRuta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRuta.setText("jLabel19");

        javax.swing.GroupLayout Foto_ContainerLayout = new javax.swing.GroupLayout(Foto_Container);
        Foto_Container.setLayout(Foto_ContainerLayout);
        Foto_ContainerLayout.setHorizontalGroup(
            Foto_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Foto_ContainerLayout.createSequentialGroup()
                .addComponent(lblRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Foto_ContainerLayout.setVerticalGroup(
            Foto_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Foto_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRuta))
        );

        btnExaminar.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnExaminar.setText("Examinar");
        btnExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExaminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FormRegEmpLayout = new javax.swing.GroupLayout(FormRegEmp);
        FormRegEmp.setLayout(FormRegEmpLayout);
        FormRegEmpLayout.setHorizontalGroup(
            FormRegEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormRegEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FormRegEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormRegEmpLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1311, 1311, 1311))
                    .addGroup(FormRegEmpLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addGroup(FormRegEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Foto_Container, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExaminar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(139, 139, 139)
                        .addGroup(FormRegEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        FormRegEmpLayout.setVerticalGroup(
            FormRegEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormRegEmpLayout.createSequentialGroup()
                .addGroup(FormRegEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormRegEmpLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FormRegEmpLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(FormRegEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(FormRegEmpLayout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addGap(83, 83, 83)
                                .addComponent(btnNuevo)
                                .addGap(88, 88, 88)
                                .addComponent(btnCancelar))
                            .addGroup(FormRegEmpLayout.createSequentialGroup()
                                .addComponent(Foto_Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExaminar)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FormRegEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar))
                .addGap(110, 110, 110))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FormRegEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 1311, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FormRegEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(443, 443, 443))
        );

        tabbedMntProd.addTab("Consultas", jPanel2);

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProductos.setAutoResizeMode(0);
        tblProductos.setAutoscrolls(false);
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        txtBusqueda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBusqueda.setToolTipText("Dni, Nombre, Apellido, Id, ");
        txtBusqueda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });

        jLabel20.setText("Buscar:");

        btnVerEnConsultas.setText("Ver en Consultas");
        btnVerEnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEnConsultasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1311, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVerEnConsultas)
                .addGap(240, 240, 240))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(btnVerEnConsultas))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(568, Short.MAX_VALUE))
        );

        tabbedMntProd.addTab("Datos", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedMntProd)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedMntProd)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyPressed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_txtDescripcionKeyPressed

    private void txtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtDescripcionKeyTyped

    private void txtPresentacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPresentacionKeyPressed

    }//GEN-LAST:event_txtPresentacionKeyPressed

    private void txtPresentacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPresentacionKeyTyped

    }//GEN-LAST:event_txtPresentacionKeyTyped

    private void cboCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboCategoriaItemStateChanged
        // TODO add your handling code here:
        Boolean isFirstEvent = true;

        if (this.cboCategoria.getSelectedItem() != null && !"<SELECCIONE>".equals(this.cboCategoria.getSelectedItem().toString())) {

            if (isFirstEvent && evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                isFirstEvent = false;
                cargarComboProducto(cboCategoria.getSelectedItem().toString());

            }
        }

    }//GEN-LAST:event_cboCategoriaItemStateChanged

    private void cboProductoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboProductoItemStateChanged
        // TODO add your handling code her
    }//GEN-LAST:event_cboProductoItemStateChanged

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        tabbedMntProd.setSelectedIndex(1);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        botones(false);
        campos(true);
        this.btnGuardar.setText("Actualizar");
        editMode = true;
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       
        byte[] fotoBytes = null;
        try {
            fotoBytes = Files.readAllBytes(new File(lblRuta.getText()).toPath());
        } catch (Exception e) {
            // Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Errror en convertir bytes" + e.getMessage() + e.getCause());
        }

        Producto prod = new Producto(
                Integer.parseInt(txtCodReg.getText()), 
                cboCategoria.getSelectedItem().toString(),
                cboProducto.getSelectedItem().toString(), 
                cboMarca.getSelectedItem().toString(),
                txtDescripcion.getText(),
                txtPresentacion.getText(),
                txtUniMed.getText(),
                Double.parseDouble(txtPrecioUnit.getText()), 
                Double.parseDouble(txtPrecCaja.getText()),
                Double.parseDouble(txtPrecVentaUnit.getText()), 
                Double.parseDouble(txtPrecVentaUnit.getText()), 
                Integer.parseInt(txtStockCajas.getText()), 
                Integer.parseInt(txtStockUnits.getText()), 
                cboEstadoProd.getSelectedItem().toString(),
                fotoBytes
        );
        

        if (editMode == false) {

            if (prodDao.agregarProducto(prod)) {
                JOptionPane.showMessageDialog(null, "Registro Agregado");

                tblProductos.setModel(prodDao.crearMdlProductos());
                ajustarColumnas(tblProductos, 19, 130);

            } else {
                JOptionPane.showMessageDialog(null, "Registro No agregado", "", 0);
            }
        } else {

            if (prodDao.actualizarProducto(prod)) {
                JOptionPane.showMessageDialog(null, "Registro Actualizado con exito");
                limpiarCampos();
                editMode = false;
                btnGuardar.setText("Guardar");
                tblProductos.setModel(prodDao.crearMdlProductos());
                ajustarColumnas(tblProductos, 19, 130);
            } else {
                JOptionPane.showMessageDialog(null, "No Se pudo actualizar", "", 0);

            }
        }
        campos(false);
        botones(true);
        limpiarCampos();
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        botones(false);
        campos(true);
        txtCodReg.setText(prodDao.generarCodReg());
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        String cod = (String) JOptionPane.showInputDialog("Ingrese el codigo de empleado");
        if (prodDao.eliminarProducto(cod)) {
            JOptionPane.showMessageDialog(null, "Se ha eliminado el registro");
            limpiarCampos();
            tblProductos.setModel(prodDao.crearMdlProductos());
        } else {
            JOptionPane.showMessageDialog(null, "Registro de empleado no encontrado");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        if (!editMode) {
            limpiarCampos();
            botones(true);
            campos(false);
        } else {
            int Rpta = 0;
            Rpta = JOptionPane.showConfirmDialog(null, "¿DESEA SALIR SIN GUARDAR LOS CAMBIOS?", "Mensaje al usuario",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (Rpta == 0) {
                limpiarCampos();
                botones(true);
                campos(false);
                btnGuardar.setText("Guardar");
                editMode = false;
            }
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExaminarActionPerformed
        // TODO add your handling code here:
        String ruta = utilitarios.rutaArchivo(this);
        ImageIcon img = new ImageIcon(ruta);
        Icon imagen = new ImageIcon(img.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_SMOOTH));
        this.lblFoto.setIcon(imagen);
        lblRuta.setText(ruta);

    }//GEN-LAST:event_btnExaminarActionPerformed

    private void txtBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Buscar(this.CBO_CampoConsulta.getSelectedItem().toString());
        }
    }//GEN-LAST:event_txtBusquedaKeyPressed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
        DefaultTableModel mdl = prodDao.crearMdlProductos();
        tblProductos.setModel(mdl);
        filtro = new TableRowSorter<DefaultTableModel>(mdl);
        tblProductos.setRowSorter(filtro);
        btnVerEnConsultas.setEnabled(false);
        
        limpiarCampos();
        botones(true);
        campos(false);
    }//GEN-LAST:event_formAncestorAdded

    private void txtUniMedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUniMedKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUniMedKeyPressed

    private void txtUniMedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUniMedKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUniMedKeyTyped

    private void txtPrecioUnitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioUnitKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioUnitKeyPressed

    private void txtPrecioUnitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioUnitKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioUnitKeyTyped

    private void txtPrecCajaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecCajaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecCajaKeyPressed

    private void txtPrecCajaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecCajaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecCajaKeyTyped

    private void txtPrecVentaUnitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecVentaUnitKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecVentaUnitKeyPressed

    private void txtPrecVentaUnitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecVentaUnitKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecVentaUnitKeyTyped

    private void txtPrecVentaCajaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecVentaCajaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecVentaCajaKeyPressed

    private void txtPrecVentaCajaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecVentaCajaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecVentaCajaKeyTyped

    private void txtStockCajasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockCajasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockCajasKeyPressed

    private void txtStockCajasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockCajasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockCajasKeyTyped

    private void txtStockUnitsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockUnitsKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockUnitsKeyPressed

    private void txtStockUnitsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockUnitsKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockUnitsKeyTyped

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        filtrarDatos();    
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void btnVerEnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEnConsultasActionPerformed
        // TODO add your handling code here:
        tabbedMntProd.setSelectedIndex(0);
    }//GEN-LAST:event_btnVerEnConsultasActionPerformed

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        // TODO add your handling code here:
        if(!editMode){
            btnVerEnConsultas.setEnabled(true);
            int selected = tblProductos.getSelectedRow();
            String codProd = tblProductos.getValueAt(selected, 0).toString();
            Producto producto = prodDao.crearProducto(codProd);
            limpiarCampos();
            cargarVista(producto);
            
        }else{
            JOptionPane.showMessageDialog(null,"Tiene Datos que aun no ha guardado");
        }
    }//GEN-LAST:event_tblProductosMouseClicked

    private void txtPresentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPresentacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPresentacionActionPerformed

    void ajustarColumnas(JTable tbl, int numCols, int size) {

        for (int i = 0; i < numCols; i++) {
            tbl.getColumnModel().getColumn(i).setPreferredWidth(size);
        }

    }

    void cargarVista(Producto produ) {
        txtCodReg.setText(String.valueOf(produ.getCod()));
        cboCategoria.setSelectedItem(produ.getCategoria());
        cboProducto.setSelectedItem(produ.getProducto());
        cboMarca.setSelectedItem(produ.getMarca());
        txtDescripcion.setText(produ.getDescripcion());
        txtPresentacion.setText(produ.getPresentacion());
        txtUniMed.setText(produ.getUniMed());
        txtPrecioUnit.setText(String.valueOf(produ.getPrecUnit()));
        txtPrecCaja.setText(String.valueOf(produ.getPrecCaja()));
        txtPrecVentaUnit.setText(String.valueOf(produ.getPrecVentaUnit()));
        txtPrecVentaCaja.setText(String.valueOf(produ.getPrecVentaCaja()));
        txtStockCajas.setText(String.valueOf(produ.getStockCaja()));
        txtStockUnits.setText(String.valueOf(produ.getStockUnid()));
        cboEstadoProd.setSelectedItem(produ.getEstado());

        
        cargarFoto(produ.getFoto());
        
    }

    void limpiarCampos() {
        txtCodReg.setText("");
        
        cargarCombo(cboCategoria, "Tb_Categoria", "Categoria");
        cargarComboProducto(null);
        cargarCombo(cboMarca,"Tb_Marca","Marca");
        
        txtDescripcion.setText("");
        txtPresentacion.setText("");
        txtUniMed.setText("");
        txtPrecioUnit.setText("");
        txtPrecCaja.setText("");
        txtPrecVentaCaja.setText("");
        txtPrecVentaUnit.setText("");
        txtStockCajas.setText("");
        txtStockUnits.setText("");
        cboEstadoProd.removeAllItems();
        cboEstadoProd.addItem("<SELECCIONE>");
        cboEstadoProd.addItem("Disponible");
        cboEstadoProd.addItem("Agotado");
        lblFoto.setIcon(null);

    }

    public void botones(boolean b) {
        btnNuevo.setEnabled(b);
        btnGuardar.setEnabled(!b);
        btnExaminar.setEnabled(!b);
        btnCancelar.setEnabled(!b);
        btnBuscar.setEnabled(b);
        btnEliminar.setEnabled(b);
        btnEditar.setEnabled(b);
    }

    public void campos(boolean b) {
        txtCodReg.setEnabled(false);
        cboCategoria.setEnabled(b);
        cboProducto.setEnabled(b);
        cboMarca.setEnabled(b);
        txtDescripcion.setEnabled(b);
        txtPresentacion.setEnabled(b);
        txtUniMed.setEnabled(b);
        txtPrecioUnit.setEnabled(b);
        txtPrecCaja.setEnabled(b);
        txtPrecVentaCaja.setEnabled(b);
        txtPrecVentaUnit.setEnabled(b);
        txtStockCajas.setEnabled(b);
        txtStockUnits.setEnabled(b);
        cboEstadoProd.setEnabled(b);


    }

    public void cargarCombo(JComboBox combo, String tbl, String dboCol) {
        combo.removeAllItems();
        combo.addItem("<SELECCIONE>");

        try {
            String sql = "select " + dboCol + " from " + tbl;
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                combo.addItem(rs.getString(1));
            }
        } catch (SQLException Error) {
            JOptionPane.showMessageDialog(null, "Error en Cargar Combo" + Error.getMessage(), "",
                    JOptionPane.ERROR_MESSAGE);
        }

    }
    public void cargarComboProducto(String categoria){
        cboProducto.removeAllItems();
        cboProducto.addItem("<SELECCIONE>");
        try {
            String sql = "declare @CodCateg char(5)\n" +
                        "select @CodCateg = CodCategoria from Tb_Categoria\n" +
                        "where Tb_Categoria.Categoria = '"+ categoria +"'\n" +
                        "\n" +
                        "select Producto from Tb_Producto where  CodCategoria  = @CodCateg";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                cboProducto.addItem(rs.getString(1));
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en Cargar Combo" + e.getMessage(), "",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    void cargarFoto(byte[] bytesArr) {
        try {

            if (bytesArr != null) {

                InputStream is = new ByteArrayInputStream(bytesArr);
                BufferedImage img = ImageIO.read(is);
                File archivo = new File("img.jpg");

                ImageIO.write(img, "jpg", archivo);

                ImageIcon imagen = new ImageIcon(archivo.getAbsolutePath());
                Icon icoImg = new ImageIcon(imagen.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_SMOOTH));
                lblFoto.setIcon(icoImg);
            } else {
                lblRuta.setText("No se ha encontrado una imagen en la base de datos del usuario");
            }

        } catch (IOException e) {
            System.out.println("Ha ocurrido un error garrafal " + e.getMessage() + e.getStackTrace());
        }
    }
    
    void filtrarDatos(){
        try {
           filtro.setRowFilter(javax.swing.RowFilter.regexFilter(this.txtBusqueda.getText()));
        } catch (Exception e) {
        }
    }
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FormRegEmp;
    private javax.swing.JPanel Foto_Container;
    private javax.swing.JToggleButton btnBuscar;
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JToggleButton btnEditar;
    private javax.swing.JToggleButton btnEliminar;
    private javax.swing.JButton btnExaminar;
    private javax.swing.JToggleButton btnGuardar;
    private javax.swing.JToggleButton btnNuevo;
    private javax.swing.JButton btnVerEnConsultas;
    private javax.swing.JComboBox<String> cboCategoria;
    private javax.swing.JComboBox<String> cboEstadoProd;
    private javax.swing.JComboBox<String> cboMarca;
    private javax.swing.JComboBox<String> cboProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblRuta;
    private javax.swing.JTabbedPane tabbedMntProd;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCodReg;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtPrecCaja;
    private javax.swing.JTextField txtPrecVentaCaja;
    private javax.swing.JTextField txtPrecVentaUnit;
    private javax.swing.JTextField txtPrecioUnit;
    private javax.swing.JTextField txtPresentacion;
    private javax.swing.JTextField txtStockCajas;
    private javax.swing.JTextField txtStockUnits;
    private javax.swing.JTextField txtUniMed;
    // End of variables declaration//GEN-END:variables
}
