/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import Model.Session;
import Model.Usuario;
import com.formdev.flatlaf.intellijthemes.FlatArcIJTheme;
import dao.Conexion;
import dao.UsuarioDao;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import gui.MantenimientoForms.Contratos;
import gui.MantenimientoForms.Empleados;
import gui.MantenimientoForms.Usuarios;

/**
 *
 * @author clide
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Metodo 
     */
    
    UsuarioDao usuDao = new UsuarioDao();
    JPanel  cnt = this.Container;
    public FrmMain() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        Conexion cn = new Conexion();
        cn.getCn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flatAtomOneDarkContrastIJTheme1 = new com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatAtomOneDarkContrastIJTheme();
        flatArcOrangeIJTheme1 = new com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme();
        Salidas_Container = new javax.swing.JPanel();
        Container = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuMantenimiento = new javax.swing.JMenu();
        itemEmp = new javax.swing.JMenuItem();
        itemProd = new javax.swing.JMenuItem();
        itemContrat_Emp = new javax.swing.JMenuItem();
        itemUsuarios = new javax.swing.JMenuItem();
        menuCerrarSesion = new javax.swing.JMenu();
        menuIniciarSesion = new javax.swing.JMenu();
        menuMiPerfil = new javax.swing.JMenu();
        menuAcercade = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        menuNombres = new javax.swing.JMenu();
        menuPerfil = new javax.swing.JMenu();

        javax.swing.GroupLayout Salidas_ContainerLayout = new javax.swing.GroupLayout(Salidas_Container);
        Salidas_Container.setLayout(Salidas_ContainerLayout);
        Salidas_ContainerLayout.setHorizontalGroup(
            Salidas_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1046, Short.MAX_VALUE)
        );
        Salidas_ContainerLayout.setVerticalGroup(
            Salidas_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1320, Short.MAX_VALUE)
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        getContentPane().add(Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 670));

        jMenu1.setText("Inicio");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        menuMantenimiento.setText("Mantenimiento");
        menuMantenimiento.setMargin(new java.awt.Insets(3, 10, 3, 10));

        itemEmp.setText("Empleados");
        itemEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEmpActionPerformed(evt);
            }
        });
        menuMantenimiento.add(itemEmp);

        itemProd.setText("Productos");
        menuMantenimiento.add(itemProd);

        itemContrat_Emp.setText("Contrato de Empleados");
        itemContrat_Emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemContrat_EmpActionPerformed(evt);
            }
        });
        menuMantenimiento.add(itemContrat_Emp);

        itemUsuarios.setText("Usuarios");
        itemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUsuariosActionPerformed(evt);
            }
        });
        menuMantenimiento.add(itemUsuarios);

        jMenuBar1.add(menuMantenimiento);

        menuCerrarSesion.setText("Cerrar Sesion");
        menuCerrarSesion.setMargin(new java.awt.Insets(3, 10, 3, 10));
        menuCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCerrarSesionMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuCerrarSesion);

        menuIniciarSesion.setText("Iniciar Sesión");
        menuIniciarSesion.setMargin(new java.awt.Insets(3, 10, 3, 10));
        menuIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuIniciarSesionMouseClicked(evt);
            }
        });
        menuIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIniciarSesionActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuIniciarSesion);

        menuMiPerfil.setText("Mi Perfil");
        menuMiPerfil.setMargin(new java.awt.Insets(3, 10, 3, 10));
        jMenuBar1.add(menuMiPerfil);

        menuAcercade.setText("Acerca De");
        menuAcercade.setMargin(new java.awt.Insets(3, 10, 3, 10));
        jMenuBar1.add(menuAcercade);

        jMenu7.setEnabled(false);
        jMenu7.setMinimumSize(new java.awt.Dimension(50, 6));
        jMenu7.setPreferredSize(new java.awt.Dimension(50, 6));
        jMenuBar1.add(jMenu7);

        menuNombres.setText("[Nombres]");
        menuNombres.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuNombres.setEnabled(false);
        menuNombres.setFocusable(false);
        menuNombres.setMargin(new java.awt.Insets(3, 0, 3, 0));
        jMenuBar1.add(menuNombres);

        menuPerfil.setText("[perfil_usuario]");
        menuPerfil.setBorderPainted(false);
        menuPerfil.setContentAreaFilled(false);
        menuPerfil.setEnabled(false);
        menuPerfil.setFocusable(false);
        menuPerfil.setMargin(new java.awt.Insets(3, 12, 3, 12));
        menuPerfil.setRequestFocusEnabled(false);
        menuPerfil.setRolloverEnabled(false);
        menuPerfil.setVerifyInputWhenFocusTarget(false);
        jMenuBar1.add(menuPerfil);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuIniciarSesionMouseClicked
        // TODO add your handling code here:
        System.out.println("Hola desde el menu bar");
        
    }//GEN-LAST:event_menuIniciarSesionMouseClicked

    private void menuIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIniciarSesionActionPerformed
        // TODO add your handling code here:
        System.out.println("iniciar Sesion..");
    }//GEN-LAST:event_menuIniciarSesionActionPerformed

    private void itemEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEmpActionPerformed
        // TODO add your handling code here:
        Empleados empleados = new Empleados();
        cargarPane(empleados);
        
        
    }//GEN-LAST:event_itemEmpActionPerformed

    private void menuCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCerrarSesionMouseClicked
        // TODO add your handling code here:
        System.out.println("cerrando Sesion..");
        int answ = JOptionPane.showConfirmDialog(null, "", this.getTitle(), JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(answ == 0){
            Session.setSession("");
            this.setVisible(false);
            
        }
        
    }//GEN-LAST:event_menuCerrarSesionMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // 
            Inicio home = new Inicio();
            cargarPane(home);
            String codEmp = Session.getSession();
            if(!"".equals(codEmp)){
                Usuario usuario = usuDao.crearUsuario(codEmp);
                this.menuNombres.setText(usuario.getApellidos() + " " + usuario.getNombres());
                this.menuPerfil.setText(usuario.getRol());
                if("Administrativo".equals(usuario.getRol())){
                    this.setTitle(Session.getTitle2());
                }else{
                    this.setTitle(Session.getTitle1());
                }
            }
            
        
        
    }//GEN-LAST:event_formWindowOpened

    private void itemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsuariosActionPerformed
        // TODO add your handling code here:
        Usuarios usr = new Usuarios();
        cargarPane(usr);
    }//GEN-LAST:event_itemUsuariosActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        System.out.println("Revalidando..");
        Inicio home = new Inicio();
        cargarPane(home);
         
    }//GEN-LAST:event_jMenu1MouseClicked

    private void itemContrat_EmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemContrat_EmpActionPerformed
        // TODO add your handling code here:
        Contratos contratos = new Contratos();
        cargarPane(contratos);
    }//GEN-LAST:event_itemContrat_EmpActionPerformed
    void  cargarPane(JPanel frm){
         frm.setSize(Container.getWidth(),Container.getHeight());
         frm.setLocation(0,0);
         this.Container.removeAll();
         this.Container.add(frm,BorderLayout.CENTER);
         this.Container.revalidate();
         this.Container.repaint();
     }
    
    /**public void CambiarEstiloBTN(JLabel l){
      JLabel[] Botones = {this.btnAlmacen,this.btnProductos,this.btnKardex,this.btnEntradas,this.btnSalidas,this.btnReportes};
      for (JLabel elem: Botones) {
      //System.out.print(Botones[elem]);
        elem.setForeground(Color.BLACK);
        elem.setBorder(BorderFactory.createLineBorder(Color.BLACK));
      }
      l.setForeground(Color.BLUE);
      l.setBorder(BorderFactory.createLineBorder(Color.BLUE));
    }*/
    
    public static void main(String args[]) {
        try {
           FlatArcIJTheme.setup();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JPanel Salidas_Container;
    private com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme flatArcOrangeIJTheme1;
    private com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatAtomOneDarkContrastIJTheme flatAtomOneDarkContrastIJTheme1;
    private javax.swing.JMenuItem itemContrat_Emp;
    private javax.swing.JMenuItem itemEmp;
    private javax.swing.JMenuItem itemProd;
    private javax.swing.JMenuItem itemUsuarios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAcercade;
    private javax.swing.JMenu menuCerrarSesion;
    private javax.swing.JMenu menuIniciarSesion;
    private javax.swing.JMenu menuMantenimiento;
    private javax.swing.JMenu menuMiPerfil;
    private javax.swing.JMenu menuNombres;
    private javax.swing.JMenu menuPerfil;
    // End of variables declaration//GEN-END:variables
}
